#!/usr/bin/env bash
set -euo pipefail

# Dynamic Hypridle Manager (updated)
# - Fixes get_power_profile bug
# - Treats 0 timeout = disabled for dim/lock/screen-off/suspend listeners
# - Ensures DPMS is restored on resume
# Based on your original hypridle-manager.sh. :contentReference[oaicite:5]{index=5}

HYPRIDLE_CONF="$HOME/.config/hypr/hypridle.conf"
HYPRIDLE_BASE_CONF="$HOME/.config/hypr/hypridle.base.conf"
CHECK_INTERVAL=${CHECK_INTERVAL:-5}
LOG_FILE="${LOG_FILE:-$HOME/.cache/hypridle-manager.log}"

# Performance: never suspend, never turn off display, lock after 5 min
PERF_DIM_TIMEOUT=0
PERF_LOCK_TIMEOUT=300
PERF_SCREEN_OFF_TIMEOUT=0
PERF_SUSPEND_TIMEOUT=0

# Balanced defaults (kept similar)
BAL_DIM_TIMEOUT=600
BAL_LOCK_TIMEOUT=300
BAL_SCREEN_OFF_TIMEOUT=330
BAL_SUSPEND_TIMEOUT=1800

# Power-saver
SAVE_DIM_TIMEOUT=300
SAVE_LOCK_TIMEOUT=180
SAVE_SCREEN_OFF_TIMEOUT=210
SAVE_SUSPEND_TIMEOUT=600

log_message(){ echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"; }

# return the current power profile string
get_power_profile() {
  powerprofilesctl get 2>/dev/null || echo "balanced"
}

# get AC status (same robust method)
get_ac_status() {
  for ps in /sys/class/power_supply/*; do
    [ -f "$ps/type" ] || continue
    t=$(cat "$ps/type")
    if [ "$t" = "Mains" ] || [ "$t" = "AC" ] || [[ "$t" == USB* ]]; then
      if [ "$(cat "$ps/online" 2>/dev/null || echo 0)" -eq 1 ]; then echo 1; return; fi
    fi
  done
  echo 0
}

create_backup(){
  if [[ ! -f "$HYPRIDLE_BASE_CONF" && -f "$HYPRIDLE_CONF" ]]; then
    cp "$HYPRIDLE_CONF" "$HYPRIDLE_BASE_CONF"
    log_message "Backup created: $HYPRIDLE_BASE_CONF"
  fi
}

# generate hypridle.conf but skip listeners when timeout==0
generate_hypridle_conf() {
  local dim_timeout=$1
  local lock_timeout=$2
  local screen_off_timeout=$3
  local suspend_timeout=$4
  local profile=$5

  cat > "$HYPRIDLE_CONF" <<-EOF
# Auto-generated by hypridle-manager.sh based on power profile: $profile
# Original backed up at: $HYPRIDLE_BASE_CONF
# Last updated: $(date '+%Y-%m-%d %H:%M:%S')

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}
EOF

  # dim (only if >0)
  if [[ "$dim_timeout" -gt 0 ]]; then
    cat >> "$HYPRIDLE_CONF" <<-EOF

# Screen dim
listener {
    timeout = $dim_timeout
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}
EOF
  fi

  # lock (only if >0)
  if [[ "$lock_timeout" -gt 0 ]]; then
    cat >> "$HYPRIDLE_CONF" <<-EOF

# Screen lock
listener {
    timeout = $lock_timeout
    on-timeout = loginctl lock-session
}
EOF
  fi

  # screen off (only if >0)
  if [[ "$screen_off_timeout" -gt 0 ]]; then
    cat >> "$HYPRIDLE_CONF" <<-EOF

# Screen off
listener {
    timeout = $screen_off_timeout
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
EOF
  fi

  # suspend (only if >0)
  if [[ "$suspend_timeout" -gt 0 ]]; then
    cat >> "$HYPRIDLE_CONF" <<-EOF

# Suspend
listener {
    timeout = $suspend_timeout
    on-timeout = systemctl suspend
    on-resume = hyprctl dispatch dpms on
}
EOF
  else
    cat >> "$HYPRIDLE_CONF" <<-EOF

# Suspend disabled for this profile
# listener { ... }
EOF
  fi
}

# reload hypridle (SIGUSR1 or restart)
reload_hypridle() {
  if pgrep -x "hypridle" >/dev/null 2>&1; then
    pkill -SIGUSR1 hypridle 2>/dev/null || {
      log_message "SIGUSR1 failed, restarting hypridle"
      pkill hypridle 2>/dev/null || true
      sleep 1
      hypridle >/dev/null 2>&1 &
    }
    log_message "hypridle reloaded"
  else
    hypridle >/dev/null 2>&1 &
    log_message "hypridle started"
  fi
}

update_hypridle_config() {
  local profile="$1"; local ac_status="$2"
  local dim_timeout lock_timeout screen_off_timeout suspend_timeout

  case "$profile" in
    performance)
      dim_timeout=$PERF_DIM_TIMEOUT
      lock_timeout=$PERF_LOCK_TIMEOUT
      screen_off_timeout=$PERF_SCREEN_OFF_TIMEOUT
      suspend_timeout=$PERF_SUSPEND_TIMEOUT
    ;;
    power-saver)
      dim_timeout=$SAVE_DIM_TIMEOUT
      lock_timeout=$SAVE_LOCK_TIMEOUT
      screen_off_timeout=$SAVE_SCREEN_OFF_TIMEOUT
      suspend_timeout=$SAVE_SUSPEND_TIMEOUT
    ;;
    balanced|*)
      dim_timeout=$BAL_DIM_TIMEOUT
      lock_timeout=$BAL_LOCK_TIMEOUT
      screen_off_timeout=$BAL_SCREEN_OFF_TIMEOUT
      suspend_timeout=$BAL_SUSPEND_TIMEOUT
    ;;
  esac

  generate_hypridle_conf "$dim_timeout" "$lock_timeout" "$screen_off_timeout" "$suspend_timeout" "$profile"
  reload_hypridle

  local suspend_msg="suspend disabled"
  if [[ "$suspend_timeout" -gt 0 ]]; then suspend_msg="suspend after $((suspend_timeout/60))min"; fi
  log_message "Hypridle updated: profile=$profile (dim=${dim_timeout}s lock=${lock_timeout}s screen_off=${screen_off_timeout}s $suspend_msg)"
}

# main
log_message "Starting hypridle-manager"
create_backup

# wait for power-profiles-daemon
retries=0
while [[ $retries -lt 20 ]]; do
  if powerprofilesctl get >/dev/null 2>&1; then break; fi
  ((retries++)); sleep 1
done

if [[ $retries -ge 20 ]]; then log_message "power-profiles-daemon not ready, defaulting to balanced"; fi

# initial
current_profile=$(get_power_profile)
current_ac=$(get_ac_status)
update_hypridle_config "$current_profile" "$current_ac"

prev_profile="$current_profile"
prev_ac="$current_ac"

while true; do
  sleep "$CHECK_INTERVAL"
  if ! pgrep -x "Hyprland" >/dev/null 2>&1; then log_message "Hyprland not running, exiting"; exit 0; fi

  current_profile=$(get_power_profile)
  current_ac=$(get_ac_status)

  if [[ "$current_profile" != "$prev_profile" || "$current_ac" != "$prev_ac" ]]; then
    update_hypridle_config "$current_profile" "$current_ac"
    log_message "State changed: $prev_profile->$current_profile, AC $prev_ac->$current_ac"
    prev_profile="$current_profile"
    prev_ac="$current_ac"
  fi
done
